Feat: Rework standalone linting action
Download of additional dependencies is now optional and there is no default
URL. Pre-commit is installed separately and it will automatically download
whatever the dependencies are for MyPy, given it installs linters in a venv.
The python version is now an optional input, so the hard coded value is now
at the top of the file. The /tmp directory is now used for the requirements
file when it is downloaded. I've updated the reusable workflow example but
removed in from the README.md documentation.

Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/actions/standalone-linting-action/action.yaml b/.github/actions/standalone-linting-action/action.yaml
--- a/.github/actions/standalone-linting-action/action.yaml
+++ b/.github/actions/standalone-linting-action/action.yaml
@@ -2,9 +2,9 @@
 # SPDX-License-Identifier: Apache-2.0
 # SPDX-FileCopyrightText: 2024 The Linux Foundation
 
-# standalone-standalone-linting-action
-name: "Linting action"
-description: "Runs linting tools that do NOT work under pre-commit.ci"
+# standalone-linting-action
+name: "Standalone Linting"
+description: "Runs linting tools that do NOT run under pre-commit.ci"
 
 inputs:
   CONFIG_URL:
@@ -14,55 +14,89 @@ inputs:
     # yamllint disable-line rule:line-length
     default: "https://raw.githubusercontent.com/lfit/releng-reusable-workflows/refs/heads/main/.github/actions/standalone-linting-action/pre-commit-config.yaml"
   DEPENDENCIES_URL:
-    description: "Download location for Python dependencies"
+    description: "Download location for additional Python dependencies"
     type: string
     required: false
+  REMOTE_CONFIG:
     # yamllint disable-line rule:line-length
-    default: "https://raw.githubusercontent.com/lfit/releng-reusable-workflows/refs/heads/main/.github/actions/standalone-linting-action/requirements.txt"
+    description: "Ignore local linting configuration; always install from remote"
+    type: string
+    required: false
+    default: "true"
+  PYTHON-VERSION:
+    description: "Python version used to run pre-commit hooks"
+    type: string
+    required: false
+    # Needs to be maintained; best practice is pass explicitly to setup-python
+    default: "3.12"
 
 runs:
   using: "composite"
   steps:
+    - name: "Checkout repository"
+      # yamllint disable-line rule:line-length
+      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
     - name: "Setup Python"
       # yamllint disable-line rule:line-length
       uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
       with:
-        python-version: "3.12"
+        python-version: ${{ inputs.python-version }}
+        cache: "pip"
 
-    - name: "Checkout repository"
-      # yamllint disable-line rule:line-length
-      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+    - name: "Install pre-commit"
+      shell: bash
+      run: pip install --disable-pip-version-check pre-commit
 
     - name: "Check prerequisites"
       shell: bash
       run: |
         # Check prerequisites
         CURL_CMD=$(which curl)
-        if [ ! -x "$CURL_CMD" ]; then echo "curl binary not found"; exit 1; fi
+        if [ ! -x "$CURL_CMD" ]; then
+         echo "cURL binary not found ❌"; exit 1
+        fi
 
-    - name: "Download Python dependencies file"
+    - name: "Check for local linting configuration"
+      if: inputs.REMOTE_CONFIG != 'true'
+      id: local-precommit-config
+      # yamllint disable-line rule:line-length
+      uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@473a3c654d58fa0c27f91a9cc25bd9433de43d5e # v0.2.4
+      with:
+        path: ".pre-commit-config.yaml"
+
+    - name: "Download remote pre-commit configuration"
+      # yamllint disable-line rule:line-length
+      if: steps.local-precommit-config.outputs != 'file' || inputs.REMOTE_CONFIG == 'true'
       shell: bash
       run: |
-        # Download Python dependencies file
-        echo "Downloading configuration from: ${{ inputs.DEPENDENCIES_URL }}"
-        curl -sS -o requirements.txt "${{ inputs.DEPENDENCIES_URL }}"
-        echo "Python dependencies file downloaded ✅"
-        cat requirements.txt
-
-    - name: "Install Python dependencies"
-      shell: bash
-      run: |
-        # Install Python dependencies
-        pip install --disable-pip-version-check --upgrade -r requirements.txt
-
-    - name: "Download pre-commit configuration file"
-      shell: bash
-      run: |
-        # Download pre-commit configuration file
-        echo "Downloading configuration from: ${{ inputs.CONFIG_URL }}"
+        # Download remote pre-commit configuration
+        echo "Downloading configuration from:"
+        echo "${{ inputs.CONFIG_URL }}"
+        # cURL will overwrite any pre-existing local file
         curl -sS -o .pre-commit-config.yaml "${{ inputs.CONFIG_URL }}"
         echo "Pre-commit configuration file downloaded ✅"
-        cat .pre-commit-config.yaml
+
+    - name: "Download Python dependencies configuration"
+      if: inputs.DEPENDENCIES_URL != ''
+      shell: bash
+      run: |
+        # Download Python dependencies configuration
+        echo "Downloading configuration from:"
+        echo "${{ inputs.DEPENDENCIES_URL }}"
+        # yamllint disable-line rule:line-length
+        if (curl -sS -o /tmp/requirements.txt \
+          "${{ inputs.DEPENDENCIES_URL }}"); then
+          echo "Python dependencies file downloaded ✅"
+        else
+          echo "Error: unable to download Python dependencies configuration ❌"
+          exit 1
+        fi
+
+    - name: "Install additional Python dependencies"
+      if: inputs.DEPENDENCIES_URL != ''
+      shell: bash
+      run: pip install --disable-pip-version-check -r /tmp/requirements.txt
 
     - name: "Validate configuration"
       shell: bash
